
version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: qindil
      POSTGRES_PASSWORD: qindil_pass
      POSTGRES_DB: qindil_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://qindil:qindil_pass@postgres:5432/qindil_dev
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      JWT_SECRET: devsecret
      NOTIF_PROVIDER: dev
    ports:
      - "4000:4000"

volumes:
  pgdata:
